mod markdown;
mod model;
mod validation;

pub use markdown::compile_markdown;
pub use model::{
    DesignSpec, Evidence, EvidenceRegion, Metadata, Platform, Rule, RuleKind, RuleScope,
    RuleSource, RuleStatus, Uncertainty,
};
pub use validation::{ValidationError, ValidationIssue};

use ts_rs::TS;

pub fn typescript_bindings() -> String {
    let declarations = [
        RuleKind::decl(),
        RuleStatus::decl(),
        RuleScope::decl(),
        RuleSource::decl(),
        Platform::decl(),
        EvidenceRegion::decl(),
        Evidence::decl(),
        Uncertainty::decl(),
        Rule::decl(),
        Metadata::decl(),
        DesignSpec::decl(),
    ];
    let mut output = String::from("// Generated by design-core. Do not edit.\n");

    for declaration in declarations {
        output.push_str("export ");
        output.push_str(&declaration);
        output.push('\n');
    }

    output
}
