use std::{fs, path::PathBuf};

#[test]
fn export_typescript_bindings() {
    let output_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../src/generated/bindings.ts");
    let bindings = design_core::typescript_bindings();

    assert!(bindings.starts_with("// Generated by design-core. Do not edit.\n"));
    assert!(bindings
        .contains("export type RuleKind = \"observation\" | \"pattern\" | \"recommendation\";"));
    assert!(bindings.contains(
        "export type RuleStatus = \"pending\" | \"accepted\" | \"edited\" | \"rejected\";"
    ));
    assert!(bindings.contains("value: unknown | null"));

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(&output_path, bindings).unwrap();

    assert!(output_path.is_file());
}
